### PR TITLE
Bugfix/Removing output on DRM can no longer cause a crash

### LINKED ISSUE #8: Removing output on DRM for pointer example segfaults
This might have to do with how we are handling the destruction event, as that's the last thing that shows up in the logs.

EDIT: According to the coredump, it fails during the pointer move event for the `pointer` example (note that the `simple` example works fine)

### PR DESCRIPTION
**Pull request by Timidger**
Fixes #8.

This fixes the issue where you can unplug a monitor during the pointer example and it would segfault unless you remembered to remove the output from the `OutputLayout`. Now, whenever an `Output` is removed it checks if it's part of a layout and removes itself automatically.

There is one last issue we have with `Output` that isn't exactly unsafe but is undesirable. Right now we don't clean up `Output` correctly, e.g when you remove and then re-add an output there are now two `Output` structs with associated meta data floating around. They don't collide (or at least, they shouldn't) but we shouldn't leak the memory to begin with. Will add another issue for this

### CODE REVIEW

File: src/types/output.rs [hunk 1]
```diff
@@ -21,6 +24,33 @@ pub struct OutputLayout {
 }
 
 impl Output {
+    pub unsafe fn set_user_data(&mut self, layout: Rc<RefCell<OutputLayout>>) {
```
Comment (Timidger) [inline src/types/output.rs]: We should change this it an internal struct, e.g called `OutputDate` or `OutputState` so that it's easier to extend

File: src/types/output.rs [hunk 2]
```diff
@@ -120,12 +152,17 @@ impl OutputLayout {
...
-        self.layout
+    pub unsafe fn from_ptr(layout: *mut wlr_output_layout) -> Self {
+        OutputLayout { layout }
+    }
+
+    pub fn remove(&mut self, output: &mut Output) {
+        // TODO Double check we can pass any output in here and not cause unsafety
+        unsafe { wlr_output_layout_remove(self.layout, output.to_ptr()) }
     }
 }
```
Comment (Timidger) [inline src/types/output.rs]: For the drop impl (just below this line) reclaim the user data so that the reference isn't leaked

File: src/types/output.rs [hunk 3]
```diff
@@ -120,12 +152,17 @@ impl OutputLayout {
...
     }
 
-    pub unsafe fn as_ptr(&self) -> *mut wlr_output_layout {
-        self.layout
+    pub unsafe fn from_ptr(layout: *mut wlr_output_layout) -> Self {
+        OutputLayout { layout }
+    }
+
+    pub fn remove(&mut self, output: &mut Output) {
+        // TODO Double check we can pass any output in here and not cause unsafety
```
Comment (Timidger) [inline src/types/output.rs]: e.g there's probably nothing stopping us from passing it twice...that's an issue
